//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi.Room.Web.Resources.Views.Shared {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Layout_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Sushi.Room.Web.Resources.Views.Shared._Layout_en", typeof(_Layout_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BasketSidebarPartial_Basket_Item_Delete_Text {
            get {
                return ResourceManager.GetString("BasketSidebarPartial_Basket_Item_Delete_Text", resourceCulture);
            }
        }
        
        internal static string BasketSidebarPartial_Clear_Cart_Text {
            get {
                return ResourceManager.GetString("BasketSidebarPartial_Clear_Cart_Text", resourceCulture);
            }
        }
        
        internal static string Clear_Basket_Confirm_Text {
            get {
                return ResourceManager.GetString("Clear_Basket_Confirm_Text", resourceCulture);
            }
        }
        
        internal static string Layout_Sushi_Room_Text {
            get {
                return ResourceManager.GetString("Layout_Sushi_Room_Text", resourceCulture);
            }
        }
        
        internal static string BasketSidebarPartial_Basket_Summary_SubTotal_Text {
            get {
                return ResourceManager.GetString("BasketSidebarPartial_Basket_Summary_SubTotal_Text", resourceCulture);
            }
        }
        
        internal static string BasketSidebarPartial_Basket_Summary_Total_Text {
            get {
                return ResourceManager.GetString("BasketSidebarPartial_Basket_Summary_Total_Text", resourceCulture);
            }
        }
        
        internal static string BasketSidebarPartial_VAT_Text {
            get {
                return ResourceManager.GetString("BasketSidebarPartial_VAT_Text", resourceCulture);
            }
        }
    }
}
